Support create commands
silverfin/silverfin-cli pull request #158
Opened 2024-12-18 09:37 UTC by michieldegezelle

## Description

Create commands were updated to work for partners as well (reconciliation texts, account templates and shared parts). 

Fixes # https://github.com/silverfin/silverfin-cli/issues/145

## Type of change

- [ ] Bug fix
- [X] New feature
- [ ] Breaking change

## Checklist

- [ ] README updated (if needed)
- [x] Version updated (if needed)
- [ ] Documentation updated (if needed)

2024-12-26 08:22 UTC, AgustinSilverfin requested changes

2024-12-26 08:22 UTC, AgustinSilverfin commented on index.js
> +  }
Let's use the same approach as in #153.

` cliUtils.checkPartnerSupport(options);` in each command in `bin/cli.js`

2024-12-26 08:22 UTC, AgustinSilverfin commented on index.js
> +  }
Move to `bin/cli.js`

2024-12-26 08:22 UTC, AgustinSilverfin commented on index.js
> +  }
Move to `bin/cli.js`

2024-12-26 08:22 UTC, AgustinSilverfin commented on index.js
> +  }
Move to `bin/cli.js`

2024-12-26 08:22 UTC, AgustinSilverfin commented on lib/templates/sharedPart.js
> +    }
Considering that we are already creating a `getTemplateId` in `fsUtils` we may want to create a `setTemplateId` (To use in all template types), and also with the `default` statement that throw an "invalid template type error" (that error could be useful to debug if we ever make changes that breaks this `updateTemplateId` calling a wrong type for example :smile:

2025-01-08 15:21 UTC, michieldegezelle commented
@AgustinSilverfin Review comments have been implemented

2025-01-10 08:37 UTC, AgustinSilverfin reviewed
@michieldegezelle besides those two comments, could you assign  this to someone else to have a look as well and to a functional testing?

2025-01-10 08:37 UTC, AgustinSilverfin commented on lib/utils/fsUtils.js
> +      throw "Invalid template type: ${type}";
Why `break` statements are return? I believe they should be there. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch

2025-01-10 08:37 UTC, AgustinSilverfin commented on bin/cli.js
> +    );
By adding `runCommandChecks` to create commands, we are now always forced to confirm. should we add the `---yes` flag so we can skip confirmation?

2025-01-10 12:43 UTC, michieldegezelle commented on bin/cli.js
> +    );
What exactly did you have in mind here? Would this work? 
![image](https://github.com/user-attachments/assets/04b7b764-2e9b-43ce-a0e4-473e279faee5)

2025-01-10 12:47 UTC, michieldegezelle commented
@AgustinSilverfin Not 100% sure how to always add the 'yes' option, so proposed something (see image above). Once that comment is processed, I will assign it for testing.

2025-01-10 13:16 UTC, AgustinSilverfin commented on bin/cli.js
> +    );
Yes, that's what I had I mind BUT now I think it does not make sense :smile: 
We didn't have the `--yes` flag before for a reason. Create will never overwrite anything. If template already exists, it won't do nothing.
So I think that we need to skip the prompt confirmation completely, without any new flag.
This is one of the reason why I don't like this `runCommandChecks`, because it does many things and now we need another exception (in create commands, we don't need to check the yes option).

What do you think?

2025-01-16 16:23 UTC, michieldegezelle commented
@AgustinSilverfin Can be reviewed again

2025-01-17 10:57 UTC, AgustinSilverfin approved these changes
Looks good to me. Just look at the one template I left for partner support check.

I'll approve it but have some to do a functional test before merging

2025-01-17 10:57 UTC, AgustinSilverfin commented on bin/cli.js
> +    const settings = runCommandChecks(
Should we have checkPartnerSupport? It is in all other create commands

```suggestion
    cliUtils.checkPartnerSupport(options);
    const settings = runCommandChecks(
```

2025-01-23 15:18 UTC, merged